project_token: f377dabd0f76ccaf8f0aca7c
name: crypto
jobs:
  - job_id: ea167f1b-b777-4aa8-a3aa-1035a7067762
    language: python
    name: Main
    entrypoint: main.py
    resources:
      limits:
        cpu: 6
        memory: 2Gi
